[2024-06-06T14:53:35.138+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_raw_data.ingest_user_information scheduled__2024-06-05T00:00:00+00:00 [queued]>
[2024-06-06T14:53:35.156+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_raw_data.ingest_user_information scheduled__2024-06-05T00:00:00+00:00 [queued]>
[2024-06-06T14:53:35.158+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-06-06T14:53:35.185+0000] {taskinstance.py:2214} INFO - Executing <Task(AirbyteTriggerSyncOperator): ingest_user_information> on 2024-06-05 00:00:00+00:00
[2024-06-06T14:53:35.192+0000] {standard_task_runner.py:60} INFO - Started process 557 to run task
[2024-06-06T14:53:35.197+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_raw_data', 'ingest_user_information', 'scheduled__2024-06-05T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data.py', '--cfg-path', '/tmp/tmp5uh8_2ub']
[2024-06-06T14:53:35.199+0000] {standard_task_runner.py:88} INFO - Job 90: Subtask ingest_user_information
[2024-06-06T14:53:35.289+0000] {task_command.py:423} INFO - Running <TaskInstance: ingest_raw_data.ingest_user_information scheduled__2024-06-05T00:00:00+00:00 [running]> on host 527807d72754
[2024-06-06T14:53:35.445+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ingest_raw_data' AIRFLOW_CTX_TASK_ID='ingest_user_information' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-05T00:00:00+00:00'
[2024-06-06T14:53:35.461+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-06-06T14:53:36.129+0000] {airbyte.py:86} INFO - Job 78 was submitted to Airbyte Server
[2024-06-06T14:53:36.131+0000] {airbyte.py:88} INFO - Waiting for job 78 to complete
[2024-06-06T14:53:39.149+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-06-06T14:53:42.177+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-06-06T14:53:45.198+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-06-06T14:53:48.222+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-06-06T14:53:51.252+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-06-06T14:53:54.316+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-06-06T14:53:54.328+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 111, in execute
    hook.wait_for_job(job_id=self.job_id, wait_seconds=self.wait_seconds, timeout=self.timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 141, in wait_for_job
    raise Exception(f"Encountered unexpected state `{state}` for job_id `{job_id}`")
Exception: Encountered unexpected state `failed` for job_id `78`
[2024-06-06T14:53:54.342+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=ingest_raw_data, task_id=ingest_user_information, execution_date=20240605T000000, start_date=20240606T145335, end_date=20240606T145354
[2024-06-06T14:53:54.365+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 90 for task ingest_user_information (Encountered unexpected state `failed` for job_id `78`; 557)
[2024-06-06T14:53:54.397+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-06T14:53:54.420+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
